# -*- coding: utf-8 -*-
"""Day1_live.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1L0hC0QUzkkvtNuynzUP6hvYAmGuETUSb

##Primeiros Passo
"""

x = 5

y = 2

print(x)

print(y)

print("Hello World")

z = x + y

print (z)

#na varivel não é possivel colocar espaços por isso use underline
cor_verde = "Verde"
cor_vermelha = "Vermelha"

#Já dentro da variavel no texto, pode usar o esapaços entre as palavras
ola = "Olá "
boa_noite = "Boa Noite"
print (ola + boa_noite)

"""##Codicional"""

A = input("Valor de A: ")
B = input("Valor de B: ")

#Depois de todas condicionais tem que colocar os dois pontos ":", siginifica que encerrou está condicional
if A > B:
  print("A é maior que B")
elif B > A:
  print("B é maior que A")
else:
  print("B é igual a A")