# -*- coding: utf-8 -*-
"""day2_live.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wJwiCCaHgY2kn4dsw08icY_9iqea6rxL

## Função
"""

def say_hello_from_kenzie ():
  print("Hello from Kenzie")

say_hello_from_kenzie()

def untar_forma():
  forma_untada = True
  return forma_untada

def mistura_ingredientes(ovo, leite, farinha, manteiga=""):
  massa = ovo + leite + farinha + manteiga
  if untar_forma():
    forma = massa
  return forma

def assar_bolo (forma_com_massa):
  if temperatura_forno ==180:
    forno = forma_com_massa

ovo = "ovo"
leite = "leite"
farinha = "farinha"
manteiga = "manteiga"


forma_com_massa = mistura_ingredientes("3", leite, farinha)



#Função para mutiplicar dois valores
def mutiplica (x, y):
  return x*y

mutiplica(4,4)

"""##Strings"""

def valida_string (nome):
  if nome.islower():
    print ("Está minusculo")
  else:
    print ("Não está minusculo")
  if nome.isupper():
    print ("Está maiusculo")
  else:
    print ("Não está maiusculo")
  if nome.find("tia") == -1:
    print ("tia não existe na string")
  else:
    print ("tia está na string")

  print(nome.split())
  nome_separado = nome.split()
  print ("-".join(nome_separado))

valida_string ("Maria foi visitar sua tia")



"""##Listas"""

numero = [1,2,3]

print(numero[0])

futuros_dev = ["Lucas", "Isabela", "Eduardo"]

print(futuros_dev[0])
print(futuros_dev[1])
print(futuros_dev[2])

mais_devs = ["Joel", "Priscila", "Rhuan"]

todos_os_devs = futuros_dev + mais_devs

print(todos_os_devs)

print(todos_os_devs[-1])

devs =["Davi","Eduardo","Juliana","Ana"]

# pessoa representa um item da lista, devs representa a lista
for pessoa in devs:
  print( pessoa + " manda bem no Python")

frutas = ["pera","maca","laranja"]

def encontra_fruta(f):
  for fruta in frutas:
    if fruta == f:
      print("achei a fruta")
      return
    else:
      print("Ainda estou procurando") 


  print("não achei")

encontra_fruta("maca")

number =[1,2,3]
number.append(4)
print(number)

