# -*- coding: utf-8 -*-
"""pokemon.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nE1H5qRHCpBlusloiBEKu3M-AdFKrDYU
"""

#Input é sempre string, com isso é preciso transformar para o formato ideal, no caso para inteiro "int"
mes = str(input('Digite o nome [por extenso] do mês que você nasceu: ')).upper()
dia = int(input('Digite o dia em que você nasceu [número]: '))

if mes == 'JANEIRO':
    tipo = 'terra'
elif mes == 'FEVEREIRO':
    tipo = 'lutador'
elif mes == 'MARÇO' or mes == 'MARCO':
    tipo = 'normal'
elif mes == 'ABRIL':
    tipo = 'aço'
elif mes == 'MAIO':
    tipo = 'voador'
elif mes == 'JUNHO':
    tipo = 'psiquico'
elif mes == 'JULHO':
    tipo = 'normal'
elif mes == 'AGOSTO':
    tipo = 'terra'
elif mes == 'SETEMBRO':
    tipo = 'voador'
elif mes == 'OUTUBRO':
    tipo = 'psiquico'
elif mes == 'NOVEMBRO':
    tipo = 'lutador'
elif mes == 'DEZEMBRO':
    tipo = 'aço'

if dia == 1:
    estilo = 'eletricidade'
elif dia == 2:
    estilo = 'mágico'
elif dia == 3:
    estilo = 'normal'
elif dia == 4:
    estilo = 'trevas'
elif dia == 5:
    estilo = 'dragão'
elif dia == 6:
    estilo = 'gelo'
elif dia == 7:
    estilo = 'inseto'
elif dia == 8:
    estilo = 'veneno'
elif dia == 9:
    estilo = 'eletricidade'
elif dia == 10:
    estilo = 'mágico'
elif dia == 11:
    estilo = 'fantasma'
elif dia == 12:
    estilo = 'trevas'
elif dia == 13:
    estilo = 'fogo'
elif dia == 14:
    estilo = 'grama'
elif dia == 15:
    estilo = 'água'
elif dia == 16:
    estilo = 'gelo'
elif dia == 17:
    estilo = 'eletricidade'
elif dia == 18:
    estilo = 'inseto'
elif dia == 19:
    estilo = 'veneno'
elif dia == 20:
    estilo = 'pedra'
elif dia == 21:
    estilo = 'mágico'
elif dia == 22:
    estilo = 'fantasma'
elif dia == 23:
    estilo = 'trevas'
elif dia == 24:
    estilo = 'normal'
elif dia == 25:
    estilo = 'grama'
elif dia == 26:
    estilo = 'fogo'
elif dia == 27:
    estilo = 'dragão'
elif dia == 28:
    estilo = 'água'
elif dia == 29:
    estilo = 'gelo'
elif dia == 30:
    estilo = 'veneno'
elif dia == 31:
    estilo = 'pedra'

print(f'Seu estilo pokemon é {tipo} e {estilo}')
print('Obrigado por selecionar seu tipo e estilo pokemon!')
print('Fim da execução do programa!')